name: bloc_effects
description: Cubit and Bloc abstractions and Flutter Widget that make it easy to add UI Effects to the BLoC state management.
version: 0.2.1
repository: https://github.com/DartAndrik/bloc_effects
issue_tracker: https://github.com/DartAndrik/bloc_effects/issues

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
