name: Flutter verify
on: [push, pull_request]
jobs:
  verify:
    # The type of machine to run the job on.
    runs-on: ubuntu-latest
    # Contains a sequence of tasks.
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'dev' or 'beta'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: flutter analyze
      - name: Run tests
        run: flutter test
        
